ylaakel_billeterie_homepage:
    path:     /
    defaults: { _controller: ylaakelBilleterieBundle:Billeterie:index }

ylaakel_billeterie_contact: 
    path: /contact
    defaults: { _controller: ylaakelBilleterieBundle:Billeterie:contact }

ylaakel_billeterie_commande_billet:
    path: /commande-billet
    defaults: { _controller: ylaakelBilleterieBundle:Billeterie:commande }

ylaakel_billeterie_information_billet:
    path: /information-billet-{numCommande}
    defaults: { _controller: ylaakelBilleterieBundle:Billeterie:info }

ylaakel_billeterie_paiement_billet:
    path: /paiement-billet-{numCommande}
    defaults: { _controller: ylaakelBilleterieBundle:Billeterie:paiement }

ylaakel_billeterie_confirmation_billet:
    path: /confirmation-billet-{numCommande}
    defaults: { _controller: ylaakelBilleterieBundle:Billeterie:confirmation }